apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: network-security-policy-template-${NAMESPACE}
objects:
- apiVersion: 'secops.pathfinder.gov.bc.ca/v1alpha1'
  kind: NetworkSecurityPolicy
  metadata:
    name: egress-internet
  spec:
    description: |
      allow the ${NAMESPACE} namespace to talk to the internet.
    source:
      - - $namespace=${NAMESPACE}
    destination:
      - - ext:network=any
- apiVersion: 'secops.pathfinder.gov.bc.ca/v1alpha1'
  kind: NetworkSecurityPolicy
  metadata:
    name: intra-namespace-comms
  spec:
    description: |
      allow the ${NAMESPACE} namespace to talk to itself
    source:
      - - $namespace=${NAMESPACE}
    destination:
      - - $namespace=${NAMESPACE}
- apiVersion: 'secops.pathfinder.gov.bc.ca/v1alpha1'
  kind: NetworkSecurityPolicy
  metadata:
    name: int-cluster-k8s-api-permit
  spec:
    description: |
      allow ${NAMESPACE} pods to talk to the k8s api
    destination:
    - - int:network=internal-cluster-api-endpoint
    source:
    - - $namespace=${NAMESPACE}
parameters:
- description: Namespace
  displayName: Namespace
  name: NAMESPACE
  required: true
  value: ''
