apiVersion: v1
kind: Template
metadata:
  name: ${NAME}
labels:
  template: ${NAME}
objects:
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    ports:
    - name: 4000-tcp
      port: 4000
      protocol: TCP
      targetPort: 4000
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
      app: ${NAME}
      deploymentconfig: ${NAME}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        creationTimestamp: null
        labels:
          app: ${NAME}
          deploymentconfig: ${NAME}
      spec:
        containers:
        - env:
          - name: WORKSHOP_NAME
            value: ${WORKSHOP_NAME}
          - name: WORKSHOP_FOLDER
            value: ${WORKSHOP_FOLDER}
          - name: WORKSHOP_BRANCH
            value: ${WORKSHOP_BRANCH}
          - name: GIT_URL
            value: ${GIT_URL}
          image: docker-registry.default.svc:5000/${NAMESPACE}/labs101:latest
          imagePullPolicy: Always
          name: ${NAME}
          ports:
          - containerPort: 4000
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 4000
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "1"
              memory: 512Mi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          # update path:
          volumeMounts:
          - name: ${VOLUMN_NAME}
            mountPath: workshop-labs/docs/SUMMARY.md
            readOnly: true
            subPath: SUMMARY.md
        volumes:
        - name: ${VOLUMN_NAME}
          configMap:
            defaultMode: 420
            name: ${NAME}-${VOLUMN_NAME}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    labels:
      app: ${NAME}
    name: ${NAME}
    namespace: ${NAMESPACE}
  spec:
    host: ${NAME}.pathfinder.gov.bc.ca
    port:
      targetPort: 4000-tcp
    tls:
      termination: edge
    to:
      kind: Service
      name: ${NAME}
      weight: 100
    wildcardPolicy: None
parameters:
- description: A name used for all objects
  displayName: Name
  name: NAME
  required: true
  value: ocp101-jk-labs-test
- description: A name used for all objects
  displayName: Name
  name: NAMESPACE
  required: true
  value: wpvqx7-dev
- description: List of content displaying
  displayName: volumn name
  name: VOLUMN_NAME
  required: false
  value: summary-list
- description: Workshop name
  displayName: Name
  name: WORKSHOP_NAME
  required: true
  value: developer_operations
- description: Dir for workshop content
  displayName: Name
  name: WORKSHOP_FOLDER
  required: true
  value: devops-platform-workshops/workshop-labs
- description: Repo of content
  displayName: Name
  name: GIT_URL
  required: true
  value: https://github.com/BCDevOps/devops-platform-workshops.git
- description: Github branch for current workshop
  displayName: Name
  name: WORKSHOP_BRANCH
  required: true
  value: ocp101-time-day
