// Generated by Selenium IDE
const WebDriverFactory = require('./WebDriverFactory')
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')
const {spawn, execFile} = require('child_process')
const path = require('path')
const {promisify} =require('util');
const fs =require('fs');

//const indefinitelyWaitTimeout = Number.MAX_SAFE_INTEGER;
const defaultWaitTimeout = Number.MAX_SAFE_INTEGER
const defaultDelayBeforeClickInMilliseconds = 2000
const defaultDelayAfterClickInMilliseconds = 100
const defaultLongWaitForElement = Number.MAX_SAFE_INTEGER

describe('deploy-image', function() {
  let driver
  let vars
  let studentName = 'cvarjao'
  let imageStreamName = 'rocketchat-cvarjao'
  let toolsNamespace = 'ocp101a-tools'
  let devNamespace = 'ocp101a-dev'
  function filterOverviewByName(name){
    return driver.wait(until.elementLocated(By.css("div.name-filter.ng-scope > form > div > div > input")), defaultWaitTimeout)
    .then(pointAndType(name))
  }

  async function say(sentence){
    await new Promise((resolve, reject)=>{
      const proc = spawn('say', ['-v', 'Samantha', '--rate=20', sentence]);
      proc.on("exit", (code)=>{
        if (code != 0){
          return reject(new Error(`'say' failed with exit code ${code}`))
        }
        resolve(code)
      })
    })
  }

  async function delay(delayInMilliseconds){
    return new Promise((resolve)=>{
      setTimeout(()=>{resolve(true)}, delayInMilliseconds)
    })
  }

  async function clearPointer(element){
    return driver.executeScript("let pointer=document.getElementById('cursor-pointer'); if (pointer) {pointer.setAttribute('class', 'myHiddenSeleniumCursorMarker');}").then(()=>{return element})
  }

  async function pointHereToo(element){
    let hrTime = process.hrtime();
    let timestamp = hrTime[0] * 1000000 + parseInt(hrTime[1] / 1000);
    return Promise.resolve(element).then((element)=>{
      return driver.executeScript(`let pointer=document.createElement('div'); pointer.setAttribute('id', 'cursor-pointer-${timestamp}'); pointer.setAttribute('class', 'cursor-pointer'); document.body.appendChild(pointer)`, element).then(()=>{return element})
    })
    .then((element)=>{
      return driver.executeScript("let pointerStyles=document.getElementById('cursor-pointer-styles'); if (!pointerStyles){pointerStyles=document.createElement('style'); pointerStyles.setAttribute('id', 'cursor-pointer-styles'); pointerStyles.setAttribute('type', 'text/css'); pointerStyles.innerHTML='.myHiddenSeleniumCursorMarker { visibility: hidden; } .myVisibleSeleniumCursorMarker { pointer-events: none; animation: blink-animation 1s steps(5, start) infinite; }  @keyframes blink-animation { to { opacity: 0; } }'; document.body.appendChild(pointerStyles)}", element).then(()=>{return element})
    })
    .then((element)=>{
      return driver.executeScript(`let pointer=document.getElementById('cursor-pointer-${timestamp}'); pointer.classList.add('myVisibleSeleniumCursorMarker'); pointer.setAttribute('style', 'background-color: red; position: absolute; z-index: 5000; width: '+$(arguments[0]).width()+'px; height: '+$(arguments[0]).innerHeight()+'px; top: '+$(arguments[0]).offset().top+'px; left: '+$(arguments[0]).offset().left+'px; opacity: 0.3; /*border-radius: 50%;*/ pointer-events: none;')`, element).then(()=>{return element})
    })
  }

  async function pointAndWait(element){
    return pointHere(element)
    .then(()=>{return delay(defaultDelayBeforeClickInMilliseconds)})
    .then(()=>{return delay(defaultDelayAfterClickInMilliseconds)})
  }
  async function pointHere(element){
    return Promise.resolve(element).then((element)=>{
      return driver.executeScript("let pointer=document.getElementById('cursor-pointer'); if (!pointer){pointer=document.createElement('div'); pointer.setAttribute('id', 'cursor-pointer'); document.body.appendChild(pointer)}", element).then(()=>{return element})
    })
    .then((element)=>{
      return driver.executeScript("let pointerStyles=document.getElementById('cursor-pointer-styles'); if (!pointerStyles){pointerStyles=document.createElement('style'); pointerStyles.setAttribute('id', 'cursor-pointer-styles'); pointerStyles.setAttribute('type', 'text/css'); pointerStyles.innerHTML='.myHiddenSeleniumCursorMarker { visibility: hidden; } .myVisibleSeleniumCursorMarker { pointer-events: none; animation: blink-animation 1s steps(5, start) infinite; }  @keyframes blink-animation { to { opacity: 0; } }'; document.body.appendChild(pointerStyles)}", element).then(()=>{return element})
    })
    .then((element)=>{
      return driver.executeScript("let pointer=document.getElementById('cursor-pointer'); pointer.setAttribute('class', 'myVisibleSeleniumCursorMarker'); pointer.setAttribute('style', 'background-color: red; position: absolute; z-index: 5000; width: '+$(arguments[0]).width()+'px; height: '+$(arguments[0]).innerHeight()+'px; top: '+$(arguments[0]).offset().top+'px; left: '+$(arguments[0]).offset().left+'px; opacity: 0.3; /*border-radius: 50%;*/ pointer-events: none;')", element).then(()=>{return element})
    })
  }

  before(async function() {
  })

  beforeEach(async function() {
    driver = await new WebDriverFactory().build()
    vars = {}
    this.ok=true;
  })

  afterEach(async function() {
    //await driver.quit();
    if (!this.ok) this.test.error(new Error('something went wrong'));
  })

  it('Deleting existing RocketChat', async function() {
    console.log(`Deleting existing RocketChat deployment - app=rocketchat-${studentName}`)
    await new Promise((resolve, reject)=>{
      const proc = spawn('oc', ['-n', devNamespace, 'delete', 'all', '-l', `app=rocketchat-${studentName}`, '--ignore-not-found=true']);
      proc.on("exit", (code)=>{
        //if (code != 0){
        //  return reject(new Error(`'oc delete' failed with exit code ${code}`))
        //}
        resolve(code)
      })
    })
  })

  it('Deleting existing MongoDB', async function() {
    await new Promise((resolve, reject)=>{
      console.log(`Deleting existing MongoDB deployment - mongodb-${studentName}`)
      const cwd = `${path.resolve(__dirname, '../../../101-materials')}`
      const proc = spawn('bash', ['-c', `./deleteServiceInstanceByMongoDBInstanceName.sh '${devNamespace}' 'mongodb-${studentName}'`], {cwd:cwd});
      proc.on("exit", (code)=>{
        if (code != 0){
          return reject(new Error(`'deleteServiceInstanceByMongoDBInstanceName.sh' failed with exit code ${code}`))
        }
        resolve(code)
      })
    })
  })

  it.skip('build', async function() {
    await new Promise((resolve, reject)=>{
      const args= [`-n`,`${toolsNamespace}`,`new-build`,`https://github.com/BCDevOps/devops-platform-workshops-labs/`,`--context-dir=apps/rocketchat`,`--name=${imageStreamName}`];
      const proc = spawn('oc', args);
      proc.on("exit", (code)=>{
        if (code != 0){
          return reject(new Error(`'oc' failed with exit code ${code}`))
        }
        resolve(code)
      })
    })

  })
  it('login', async function() {
    //Wait for GitHub Login
    let narration=say("Let's start by going to GitHub and make sure we are logged in. If not you will need to enter your credentials")
    await driver.get("https://github.com/login")
    await driver.wait(until.elementLocated(By.css('div.header-nav-current-user > a.user-profile-link')), defaultWaitTimeout)
    await narration
  })

  it('open openshift web console', async function() {
    narration=say("Let's go to the  OpenShift Web Console")
    //Wait for OpenShift Login
    await driver.get("https://console.pathfinder.gov.bc.ca:8443/console/catalog")
    await driver.wait(until.elementLocated(By.css('#user-dropdown > span.username.truncate.ng-binding')), defaultWaitTimeout)
    await narration
  })

  function scrollIntoView(element){
    return Promise.resolve(element)
    .then((element)=>{return driver.executeScript("arguments[0].scrollIntoView()", element).then(()=>{return element})})
  }
  function pointAndClick(element){
    return Promise.resolve(element)
    .then((element)=>{
      return pointHere(element)
    })
    .then((element)=>{return delay(defaultDelayBeforeClickInMilliseconds).then(()=>{return element})})
    .then((element)=>{
      return clearPointer(element)
    })
    .then((element)=>{
      return element.click()
    })
    .then(()=>{return delay(defaultDelayAfterClickInMilliseconds)})
  }

  function pointAndType(text){
    return function(element){
      return Promise.resolve(element).then((element)=>{
        return pointHere(element)
      })
      .then((element)=>{return delay(defaultDelayBeforeClickInMilliseconds).then(()=>{return element})})
      .then((element)=>{ return element.sendKeys('').then(()=>{return element})})
      .then((element)=>{return element.clear().then(()=>{return element})})
      .then((element)=>{
        return element.sendKeys(text).then(()=>{return element})
      })
      .then((element)=>{
        return clearPointer(element).then(()=>{return element})
      })
      .then((element)=>{return delay(defaultDelayBeforeClickInMilliseconds).then(()=>{return element})})
    }
  }

  function pointAndSelect(value){
    return function(element){
      return Promise.resolve(element)
      .then((element)=>{
        return pointHere(element)
      })
      .then((element)=>{return delay(defaultDelayBeforeClickInMilliseconds).then(()=>{return element})})
      .then((element)=>{
        return element.click()
      })
      .then((element)=>{
        return clearPointer(element)
      })
      .then(()=>{
        return driver.wait(until.elementLocated(By.css("body > div.ui-select-container.ui-select-bootstrap.dropdown.open > ul")), defaultWaitTimeout)
        .then((dropdown)=>{
          return driver.findElement(By.css(".open > .form-control")).sendKeys(value)
          .then(()=>{
            return driver.findElement(By.css(".ui-select-highlight")).click()
          })
          .then(()=>{
            return driver.wait(until.elementIsNotVisible(dropdown), defaultWaitTimeout)
          })
        })
      })
    }
  }

  it('find dev project', async function() {
    await driver.get("https://console.pathfinder.gov.bc.ca:8443/console/catalog")
    //View All
    await say('Find our "dev" project by clicking on "View All"')
    .then(()=>{
      return driver.wait(until.elementLocated(By.css('body > div.container-pf-nav-pf-vertical > div > div > div > landing-page > div.landing > div.landing-side-bar > landingside > projects-summary > div > div.catalog-project-summary-list.ng-scope > div.projects-count > a')), defaultWaitTimeout)
      .then(pointAndClick)
    })
    
    // Search for the "Openshift 101"
    await say('Enter "OpenShift 1-0-1" in the search field')
    .then(()=>{
      return driver.wait(until.elementLocated(By.css('#search-projects')), defaultWaitTimeout)
      .then(pointAndType("OpenShift 101"))
    })
    // Select the dev one
    await say('Select the "dev" one').then(()=>{
      return driver.wait(until.elementLocated(By.xpath(`//div[contains(@class, "list-pf-content-wrapper")]/div/div[contains(@class, project-name-item)]/h2/a[@title="OpenShift 101 (dev)" and substring(@href, string-length(@href)-${devNamespace.length -1}, ${devNamespace.length})="${devNamespace}"]`)), defaultWaitTimeout)
      .then(pointAndClick)
    })
  })

  it('filter overview', async function() {
    await Promise.resolve(true)
    //await say('We will filter the overview page to only show my application')
    //.then(()=>{
    //  return filterOverviewByName(`-${studentName}`);
    //})
  })

  it('deploy-rocketchat', async function() {
    await driver.get(`https://console.pathfinder.gov.bc.ca:8443/console/project/${devNamespace}/overview`)
    // Click on "Add to Project" > and "Deploy Image"
    await driver.wait(until.elementLocated(By.css(".dropdown-toggle > .hidden-xs:nth-child(2)")), defaultWaitTimeout)
    .then(pointAndClick)

    await driver.wait(until.elementLocated(By.linkText("Deploy Image")), defaultWaitTimeout)
    .then(pointAndClick)

    //Wait for wizard form to show up
    await driver.wait(until.elementLocated(By.css(".wizard-pf-body")), defaultWaitTimeout).click()

    // Namespace
    await driver.wait(until.elementLocated(By.css(".form-group:nth-child(1) .ui-select-placeholder")), defaultWaitTimeout)
    .then(pointAndSelect(toolsNamespace))
     
    // ImageStream
    await driver.wait(until.elementLocated(By.css(".form-group:nth-child(2) .ui-select-placeholder")), defaultWaitTimeout)
    .then(pointAndSelect(imageStreamName))

    // ImageStream Tag
    await driver.wait(until.elementLocated(By.css(".form-group:nth-child(3) .ui-select-placeholder")), defaultWaitTimeout)
    .then(pointAndSelect("dev"))

    await driver.wait(until.elementLocated(By.id("name")), defaultWaitTimeout)
    .then((element)=>{return driver.executeScript("arguments[0].scrollIntoView()", element).then(()=>{return element})})
    .then(pointAndType(`rocketchat-${studentName}`))

    await driver.wait(until.elementLocated(By.id("nextButton")), defaultWaitTimeout)
    .then(pointAndClick)

    await driver.wait(until.elementLocated(By.linkText("Continue to the project overview")), defaultWaitTimeout)
    .then(pointAndClick)
    
    await filterOverviewByName(`rocketchat-${studentName}`);

    // .project-bar

    await driver.wait(until.elementLocated(By.xpath(`//div[contains(@class, "app-heading")]/h2[span="rocketchat-${studentName}"]/parent::div/following-sibling::div/descendant::div[@class="list-pf-chevron"]/descendant::a/span/span`)), defaultWaitTimeout)
    .then(async (element)=>{
      let clazz=await element.getAttribute("class")
      if (clazz.includes("fa-angle-down")){
        return element;
      }
      return pointAndClick(element)
    })
  })

  it('monitor-rocketchat-deployment', async function() {
    await driver.get(`https://console.pathfinder.gov.bc.ca:8443/console/project/${devNamespace}/overview`)
    await filterOverviewByName(`${studentName}`)

    await driver.wait(until.elementLocated(By.xpath(`//overview-list-row/div/div/div[contains(@class, "list-pf-content")]/div[contains(@class, "list-pf-name")]/h3/a[contains(@href, "/browse/dc/rocketchat-${studentName}")]`)), defaultLongWaitForElement)
    .then(pointAndClick)

    await driver.wait(until.elementLocated(By.css("span.latest-status > a > span")), defaultLongWaitForElement)
    .then(pointAndClick)

    await driver.wait(until.elementLocated(By.xpath(`//pod-donut/div/*[1]/*[2]/*[5]/*[4]/*[1]/*[1][. = "1"]/ancestor::pod-donut`)), defaultLongWaitForElement)
    .then(pointAndClick)

    await driver.wait(until.elementLocated(By.xpath(`//breadcrumbs/ol/li[1]/a[. = "Pods"]`)), defaultLongWaitForElement)
    await driver.wait(until.elementLocated(By.linkText("Events")), defaultLongWaitForElement).click()
    await driver.wait(until.elementLocated(By.xpath("//events/div/table/tbody/tr/td[@data-title=\"Reason\" and span =\"Started\"]")), defaultLongWaitForElement)
    .then(pointHere)
    .then(clearPointer)

    await driver.wait(until.elementLocated(By.linkText("Logs")), defaultLongWaitForElement).click()


    await driver.wait(until.elementLocated(By.xpath('//span[contains(@class, "container-state")]/span[. = "Crash loop back off"]')), defaultLongWaitForElement)
    .then(pointHere)

    await driver.wait(until.elementLocated(By.xpath('//log-viewer/div[2]/div/div[2]/table/tbody/tr[@class="log-line"]/td[@class="log-line-text"][contains(., "MongoError: failed to connect to server [mongo:27017] on first connect [MongoError: getaddrinfo ENOTFOUND mongo mongo:27017]")]')), defaultLongWaitForElement)
    .then(pointHereToo)
  })

  it('deploy-mongodb', async function() {
    await driver.get(`https://console.pathfinder.gov.bc.ca:8443/console/project/${devNamespace}/overview`)
    await driver.wait(until.elementLocated(By.id("search-input")), defaultWaitTimeout)
    .then((element)=>{return element.click().then(()=>{return element})})
    .then((element)=>{return element.sendKeys("mongodb ephemeral").then(()=>{return element})})
    .then((element)=>{
      return element.getAttribute("aria-owns")
    })
    .then((dropDownID)=>{
      return driver.wait(until.elementLocated(By.css(`#${dropDownID}-option-0 .catalog-search-match-label`)), defaultWaitTimeout)
      .then(element=>{
        return element.click();
      })
    })

    await driver.wait(until.elementLocated(By.id("nextButton")), defaultWaitTimeout).then((element)=>{return element.click()})
    
    await driver.wait(until.elementLocated(By.id("DATABASE_SERVICE_NAME")), defaultWaitTimeout)
    .then(pointAndType(`mongodb-${studentName}`))

    await driver.wait(until.elementLocated(By.id("MONGODB_USER")), defaultWaitTimeout)
    .then(pointAndType(`dbuser`))

    await driver.wait(until.elementLocated(By.id("MONGODB_PASSWORD")), defaultWaitTimeout)
    .then(pointAndType(`dbpass`))

    await driver.wait(until.elementLocated(By.id("MONGODB_DATABASE")), defaultWaitTimeout)
    .then(pointAndType(`rocketchat`))

    await driver.wait(until.elementLocated(By.id("MONGODB_VERSION")), defaultWaitTimeout)
    .then(pointAndType(`2.6`))

    await driver.wait(until.elementLocated(By.id("nextButton")), defaultWaitTimeout)
    .then(pointAndClick)

    await driver.wait(until.elementLocated(By.css(".bind-choice:nth-child(3)")), defaultWaitTimeout)
    .then(pointAndClick)

    await driver.wait(until.elementLocated(By.id("nextButton")), defaultWaitTimeout)
    .then(pointAndClick)

    await driver.wait(until.elementLocated(By.linkText("Continue to the project overview")), defaultLongWaitForElement)
    .then(pointAndClick)
    await filterOverviewByName(`${studentName}`)
  })

  it('monitor-rocketchat-deployment', async function() {
    await driver.get(`https://console.pathfinder.gov.bc.ca:8443/console/project/${devNamespace}/overview`)
    await filterOverviewByName(`${studentName}`)

    await driver.wait(until.elementLocated(By.xpath(`//overview-list-row/div/div/div[contains(@class, "list-pf-content")]/div[contains(@class, "list-pf-name")]/h3/a[contains(@href, "/browse/dc/mongodb-${studentName}")]`)), defaultLongWaitForElement)
    .then(pointAndClick)

    await driver.wait(until.elementLocated(By.css("span.latest-status > a > span")), defaultLongWaitForElement)
    .then(pointAndClick)

    await driver.wait(until.elementLocated(By.xpath(`//pod-donut/div/*[1]/*[2]/*[5]/*[4]/*[1]/*[1][. = "1"]/ancestor::pod-donut`)), defaultLongWaitForElement)
    .then(pointAndClick)

    await driver.wait(until.elementLocated(By.xpath(`//breadcrumbs/ol/li[1]/a[. = "Pods"]`)), defaultLongWaitForElement)
    await driver.wait(until.elementLocated(By.linkText("Events")), defaultLongWaitForElement).click()
    await driver.wait(until.elementLocated(By.xpath("//events/div/table/tbody/tr/td[@data-title=\"Reason\" and span =\"Started\"]")), defaultLongWaitForElement)
    .then(pointHere)
    .then(clearPointer)

    await driver.wait(until.elementLocated(By.linkText("Logs")), defaultLongWaitForElement).click()

    await driver.wait(until.elementLocated(By.xpath('//log-viewer/div[2]/div/div[2]/table/tbody/tr[@class="log-line"]/td[@class="log-line-text"][contains(., "authenticate db: rocketchat")][1]')), defaultLongWaitForElement)
    .then(pointHere)

    await driver.wait(until.elementLocated(By.xpath('//span[contains(@class, "container-state")]/span[. = "Running"]')), defaultLongWaitForElement)
    .then(pointHere)
  })

  it('Connect RocketChat to MongoDB', async function() {
    this.timeout(120000)
    await driver.get(`https://console.pathfinder.gov.bc.ca:8443/console/project/${devNamespace}/overview`)
    await filterOverviewByName(`${studentName}`)
    
    await driver.wait(until.elementLocated(By.xpath(`//div[contains(@class,"list-pf-item")]/descendant::div[contains(@class,"list-pf-name")]/h3/a[. = "rocketchat-${studentName}"]`)), defaultLongWaitForElement)
    .then(pointAndClick)

    await driver.wait(until.elementLocated(By.xpath(`//breadcrumbs/ol/li[1]/a[. = "Deployments"]`)), defaultLongWaitForElement)
    .then(pointAndWait)

    let lastReplicationControllerNumber = await driver.wait(until.elementLocated(By.css("span.latest-status > a > span")), defaultLongWaitForElement).then((element)=>{return element.getText()}).then((text)=>{return text.substring(1)})
    await driver.findElement(By.linkText("Environment")).click()
    await driver.findElement(By.id("key-value-editor-key-1000-0"))    .then((element)=> {return element.click().then(()=>{return element})})
    .then(pointAndType("MONGO_URL"))

    await driver.findElement(By.id("key-value-editor-value-1000-0"))
    .then(pointAndType(`mongodb://dbuser:dbpass@mongodb-${studentName}:27017/rocketchat`))


    await driver.findElement(By.css("edit-environment-variables > form > div.gutter-top-bottom > button")).click()
    await driver.findElement(By.linkText("History")).click()
    await driver.wait(until.elementLocated(By.xpath(`//span[contains(@class,"latest-status")]/a[. = "#${parseInt(lastReplicationControllerNumber)+1}"]`)), defaultLongWaitForElement)
    .catch(()=>{return true})

    
    await driver.findElement(By.css("span.latest-status > a"))
    .then(pointAndClick)

    await driver.wait(until.elementLocated(By.xpath(`//pod-donut/div/*[1]/*[2]/*[5]/*[4]/*[1]/*[1][. = "1"]/ancestor::pod-donut`)), defaultLongWaitForElement)
    .then(pointAndClick)
    
    await driver.wait(until.elementLocated(By.xpath(`//breadcrumbs/ol/li[1]/a[. = "Pods"]`)), defaultLongWaitForElement)
    .then(pointAndWait)

    //Is container Ready?
    await driver.wait(until.elementLocated(By.xpath(`//uib-tab-heading[. = "Details"]/parent::*`)), defaultLongWaitForElement)
    .then(pointAndClick)
    .then(()=>{
      return driver.wait(until.elementLocated(By.xpath('//container-statuses/div/h4/parent::*/dl/dt[. = "Ready:"]/following-sibling::*[contains(., "true")]')), defaultLongWaitForElement)
    })
    .then(pointAndWait)
    .catch(()=>{
      return driver.wait(until.elementLocated(By.linkText("Events")), defaultLongWaitForElement)
      .then(pointAndClick)
      .then(()=>{
        return driver.wait(until.elementLocated(By.xpath("//events/div/table/tbody/tr/td[@data-title=\"Reason\" and span =\"Started\"]")), defaultLongWaitForElement)
        .then(pointAndWait)
      })
    })

    await driver.wait(until.elementLocated(By.linkText("Logs")), defaultLongWaitForElement)
    .then(pointAndClick)

    await driver.wait(until.elementLocated(By.xpath("//log-viewer/div[2]/div/div[2]/table/tbody/tr[@class=\"log-line\"]/td[@class=\"log-line-text\"]/span[2][. =\"|                SERVER RUNNING                |\"]")), defaultLongWaitForElement)
    .then(pointHere)
    .then(()=>{return delay(defaultDelayAfterClickInMilliseconds)})

    await driver.wait(until.elementLocated(By.xpath('//span[contains(@class, "container-state")]/span[. = "Running"]')), defaultLongWaitForElement)
    .then(pointHereToo)
  })
  it('re-play', async function() {
    await driver.get(`https://console.pathfinder.gov.bc.ca:8443/console/project/${devNamespace}/overview`)
    await filterOverviewByName(`${studentName}`)
    const time = new Date();
    try {
      fs.utimesSync(__filename, time, time);
    } catch (err) {
      fs.closeSync(fs.openSync(__filename, 'w'));
    }
  })
})
