---
- hosts: localhost
  become: false
  vars_files: 
    vars.yaml
  tasks: 
    - name: Create Projects
      include_tasks: tasks/create_environments.yaml
      with_items: "{{ workshop_name }}"
      when: action == "create"
    - name: Delete Projects
      include_tasks: tasks/delete_projects.yaml
      when: action == "delete"
