---
- name: Set project name fact
  set_fact: 
    project_name: "{{ item }}{{ project_suffix }}"
- name: Create "{{ item }}" project
  include_tasks: create_projects.yaml
  with_items: 
    - "{{ environments }}"
  loop_control: 
    loop_var: env
- name: Create "{{ item }}" project quots
  include_tasks: create_quotas.yaml
  with_items: 
    - "{{ environments }}"
  loop_control: 
    loop_var: env
