apiVersion: template.openshift.io/v1
kind: Template
metadata:
  name: ocp-lab-template
objects:
- apiVersion: v1
  kind: ConfigMap
  metadata:
    labels:
      app: ${APP}
    name: ${APP}-${COMPONENT}${SUFFIX}-${VOLUMN_NAME}
  data:
    SUMMARY-openshift101.md: |
      # Summary - 101

      * [Setup](openshift101/setup.md)

      OpenShift 101 - Developer Operations
      ---

      * [Overview](openshift101/readme.md)
      * [Builds](openshift101/01_builds.md)
      * [Registry Console](openshift101/02_registry_console.md)
      * [Deployments](openshift101/03_deployment.md)
      * [Application Availability](openshift101/04_application_availability.md)
      * [Autoscaling](openshift101/05_autoscaling.md)
      * [Persistent Storage](openshift101/06_persistent_storage.md)
      * [Persistent Configurations](openshift101/07_persistent_configurations.md)
      * [Event Streams](openshift101/08_event_streams.md)
      * [Debugging Containers](openshift101/09_debugging_containers.md)
      * [Logging and Visualizations](openshift101/10_logging_and_visualizations.md)
      * [Resource Requests and Limits](openshift101/11_resource_management.md)
      * [Pod Lifecycle](openshift101/12_pod_lifecycle.md)
    SUMMARY-openshift201.md: |
      # Summary - 201

      * [Setup](openshift201/setup.md)

      OpenShift 201 - Pipeline your DevOps
      ---

      * [Overview](openshift201/readme.md)
      * [GitFlow](openshift201/01_git_setup.md)
      * [Using OpenShift Templates](openshift201/02_templates_openshift.md)
      * [Helm Templates](openshift201/02_templates_helm.md)
      * [Building OpenShift Templates](openshift201/02_building_openshift_templates.md)
      * [Jenkins Pipeline As Code](openshift201/04_jenkins_pipeline_as_code.md)
      * [Jenkins Build Pipeline](openshift201/04_jenkins_build_pipeline.md)
      * [Jenkins Pipeline Parallelization](openshift201/04_jenkins_pipelines_parallel.md)
      * [HA DB Installation](openshift201/05_ha_db_create.md)
      * [DB Configuration](openshift201/05_ha_db_reconfigure.md)
      * [DB Backup and Restore](openshift201/06_db_backup.md)
      * [Failure Testing](openshift201/07_failover.md)
      * [Health Checks](developer_ops_201/09_health_check.md)
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: ${APP}
    name: ${APP}-${COMPONENT}${SUFFIX}
  spec:
    ports:
    - name: 4000-tcp
      port: 4000
      protocol: TCP
      targetPort: 4000
    selector:
      app: ${APP}
      deploymentconfig: ${APP}-${COMPONENT}${SUFFIX}
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: apps.openshift.io/v1
  kind: DeploymentConfig
  metadata:
    labels:
      app: ${APP}
    name: ${APP}-${COMPONENT}${SUFFIX}
  spec:
    replicas: 1
    revisionHistoryLimit: 5
    selector:
      app: ${APP}
      deploymentconfig: ${APP}-${COMPONENT}${SUFFIX}
    strategy:
      activeDeadlineSeconds: 21600
      resources: {}
      rollingParams:
        intervalSeconds: 1
        maxSurge: 25%
        maxUnavailable: 25%
        timeoutSeconds: 600
        updatePeriodSeconds: 1
      type: Rolling
    template:
      metadata:
        labels:
          app: ${APP}
          deploymentconfig: ${APP}-${COMPONENT}${SUFFIX}
      spec:
        containers:
        - env:
          - name: WORKSHOP_NAME
            value: ${WORKSHOP_NAME}
          - name: WORKSHOP_FOLDER
            value: ${WORKSHOP_FOLDER}
          - name: WORKSHOP_BRANCH
            value: ${GIT_BRANCH}
          - name: GIT_URL
            value: ${GIT_URL}
          image: ${IMAGE_REGISTRY}/${IMAGE_NAMESPACE}/${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: Always
          name: ${APP}-${COMPONENT}${SUFFIX}
          ports:
          - containerPort: 4000
            protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /
              port: 4000
              scheme: HTTP
            initialDelaySeconds: 180
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: "20m"
              memory: 1Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
          - name: ${VOLUMN_NAME}
            mountPath: /${WORKSHOP_FOLDER}/docs/summaries/SUMMARY-${WORKSHOP_NAME}.md
            subPath: SUMMARY-${WORKSHOP_NAME}.md
            readOnly: true
        volumes:
        - name: ${VOLUMN_NAME}
          configMap:
            name: ${APP}-${COMPONENT}${SUFFIX}-${VOLUMN_NAME}
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        schedulerName: default-scheduler
        securityContext: {}
        terminationGracePeriodSeconds: 30
    test: false
    triggers:
    - type: ConfigChange
- apiVersion: route.openshift.io/v1
  kind: Route
  metadata:
    annotations:
      openshift.io/host.generated: "true"
    labels:
      app: ${APP}
    name: ${APP}-${COMPONENT}${SUFFIX}
  spec:
    host: ${APP}-${COMPONENT}${SUFFIX}.pathfinder.gov.bc.ca
    tls:
      termination: edge
    port:
      targetPort: 4000-tcp
    to:
      kind: Service
      name: ${APP}-${COMPONENT}${SUFFIX}
      weight: 100
    wildcardPolicy: None
parameters:
- description: The name of the application for labeling all artifacts.
  displayName: Application Name
  name: APP
  value: ocp101
- description: The name of the application component for labeling all artifacts.
  displayName: Application Component
  name: COMPONENT
  value: labs
- description: URL Suffix to add to name
  displayName: URL Suffix
  name: SUFFIX
- description: The workshop foldername
  displayName: Workshop Folder
  name: WORKSHOP_FOLDER
  value: devops-platform-workshops/workshop-labs
- description: The name of the workshop to launch
  displayName: Workshop Name
  name: WORKSHOP_NAME
  value: openshift101
- description: Git URL
  displayName: Git URL
  name: GIT_URL
  value: https://github.com/BCDevOps/devops-platform-workshops.git
- description: Git workshop branch
  displayName: Workshop Branch
  name: GIT_BRANCH
  value: master
- description: Image registry
  displayName: Image registry
  name: IMAGE_REGISTRY
  value: docker-registry.default.svc:5000
- description: Image Source Namespace
  displayName: Image Namespace
  name: IMAGE_NAMESPACE
  value: wpvqx7-tools
- description: Image Name
  displayName: Image Name
  name: IMAGE_NAME
  value: workshop-labs
- description: Image Tag
  displayName: Image Tag
  name: IMAGE_TAG
  value: v2-stable
- description: Volumn name
  displayName: Volumn name
  name: VOLUMN_NAME
  value: summary
